### ISSUE TITLE
Does not work as intented for me

### ISSUE THREAD

**Issue by bjornsyse** [felixkosmalla/unity-vive-reality-mapper#1]
Hi Felix

I'm trying hard to get your scripts to work in current Unity 2018.2. SteamVR has updated since then, but even if I think I've gotten around that, calibration ends up wicked and I'm not sure why yet. Have you tried this recently?

**Comment by felixkosmalla** [comment]
Hi bjornsyse,

I am pretty sure a student of our used it in a 2018 Unity version. How many calibration point pairs did you used? Can you send pictures or share your scene?

Cheers
Felix

**Comment by bjornsyse** [comment]
Hi Felix! I've gone over it again now and made some modifications to the code, and now I got it working! Thanks.
